/**
 * Public surface of the policy engine.
 *
 * Import from `@/lib/policy` rather than reaching into submodules, so the
 * internal layout can change without touching call sites. Everything here is
 * dependency-free at runtime: safe from client components, `"use step"` plugin
 * files, edge middleware and the standalone executor alike.
 */

export {
  ARN_PREFIX,
  ARN_PREFIX_SEPARATOR,
  ARN_SEGMENT_SEPARATOR,
  ARN_SELECTOR_NONE,
  ARN_WILDCARD_DEEP,
  ARN_WILDCARD_SEGMENT,
  type ArnParseResult,
  type ArnPart,
  ArnSegment,
  arnMatches,
  arnStringMatches,
  buildArn,
  buildAssetArn,
  buildContractCallArn,
  buildResourceArn,
  isArnSegment,
  isConcreteArn,
  isValidAddress,
  isValidSelector,
  type ParsedArn,
  parseArn,
} from "./arn";
export {
  CAPABILITIES,
  Capability,
  type CapabilityDefinition,
  capabilityAncestors,
  capabilityMatches,
  expandCapabilityPattern,
  GuardDimension,
  getCapabilitiesByPlane,
  getCapability,
  isCapability,
  isOnchainCapability,
} from "./capabilities";
export {
  DEFAULT_POLICY_NAME,
  ENGINE_FAILURE_REASONS,
  FactProvenance,
  FactState,
  isEngineFailureReason,
  isOrgScopedPrincipalKind,
  isSignalConditionKey,
  ORG_SCOPED_PRINCIPAL_KINDS,
  POLICY_CACHE_TTL_MS,
  POLICY_LIMIT_WINDOW_SECONDS,
  POLICY_RECEIPT_TTL_MS,
  POLICY_ROLE_RANK,
  POLICY_SCHEMA_VERSION,
  POLICY_STALE_SERVE_MAX_MS,
  PolicyCheckpoint,
  PolicyConditionKey,
  PolicyDecisionReason,
  PolicyEffect,
  PolicyEnforcementMode,
  PolicyLimitMetric,
  PolicyLimitScope,
  PolicyLimitWindow,
  PolicyOperator,
  PolicyOutcome,
  PolicyPlane,
  PolicyPostconditionKey,
  PolicyReservationStatus,
  PolicyRole,
  PolicySignalKey,
  PrincipalKind,
  SIGNAL_CONDITION_PREFIX,
} from "./constants";
export {
  isPolicyDeniedError,
  POLICY_DENIAL_MESSAGE,
  PolicyDeniedError,
  type PolicyDeniedErrorInit,
  toPolicyDenial,
} from "./errors";
export {
  failClosedDecision,
  getPolicyEvaluator,
  makeDecision,
  type PolicyEvaluator,
  policySetGoverns,
  resetPolicyEvaluator,
  resolveObservedOnly,
  setPolicyEvaluator,
  shouldBlock,
  UNMANAGED_EVALUATOR,
  unmanagedDecision,
} from "./evaluator";
export {
  type ControlPlaneContext,
  enforceControlPlanePolicy,
  evaluateControlPlanePolicy,
  isSelfReferentialCapability,
  principalOrganizationId,
  principalRole,
  type RoleFloor,
  SELF_REFERENTIAL_CAPABILITY_PREFIXES,
  satisfiesRoleFloor,
} from "./middleware/control-plane-policy";
export {
  evaluateNodePolicy,
  isAllowedOutcome,
  type NodePolicyContext,
  type NodePolicyOutcome,
  withNodePolicy,
} from "./middleware/node-policy";
export type {
  AssetFact,
  CompiledPolicy,
  CompiledPolicySet,
  CompiledStatement,
  CounterpartyFact,
  CounterpartyRole,
  Fact,
  MatchedStatement,
  OrganizationPolicy,
  PolicyCompileError,
  PolicyCompileResult,
  PolicyCondition,
  PolicyConditionMap,
  PolicyConditionOperand,
  PolicyDecision,
  PolicyDocument,
  PolicyEvaluation,
  PolicyFacts,
  PolicyGuardAllowed,
  PolicyGuardBlocked,
  PolicyGuardResult,
  PolicyLimit,
  PolicyPostcondition,
  PolicyRequest,
  PolicyReservation,
  PolicySignal,
  PolicySignalBundle,
  PolicyStatement,
  Principal,
  PrincipalOrganizationId,
} from "./types";
