/**
 * Chain-scoped test data for protocol-coverage fixtures (KEEP-458).
 *
 * Authoritative for: known testnet tokens, faucet contracts, fork-mode whale
 * addresses. The persistent E2E test user's wallet address is NOT here --
 * KEEP-529 made it HSM-generated by Turnkey, so the address differs per
 * environment. Callers look it up from `organization_wallets` at test/seed
 * time and pass it into the builders in `lib/test-data/build-workflow.ts`.
 *
 * Where addresses come from:
 *   - Tokens are extracted/extended from `scripts/seed/seed-tokens.ts` and from
 *     existing usage in `tests/integration/protocol-superfluid-onchain.test.ts`.
 *   - Aave V3 Sepolia faucet is from Aave's address book (verify against
 *     https://aave.com/docs/resources/addresses before relying on it).
 *   - Mainnet whale addresses are large protocol-held balances verified via
 *     Etherscan token-holder rankings at the time of writing.
 */

/** Env var name the funder script reads. The PK itself must never appear in code. */
export const TESTNET_FUNDER_PK_ENV = "TESTNET_FUNDER_PK";

/**
 * Chain IDs where anvil fork-mode provisioning applies. On these chains
 * ensureNativeGas uses anvil_setBalance and ensureErc20Acquired uses whale
 * impersonation or an impersonated faucet mint instead of a real funder
 * EOA + testnet faucets.
 *
 * Sepolia (11155111) moved to fork mode after live-testnet runs proved
 * economically unviable on ephemeral CI: each run seeds a fresh Turnkey
 * wallet (stranding every top-up), and 2026-07-02 base-fee spikes of
 * 40-105 gwei priced a single worst-case Superfluid tx above any top-up
 * the shared funder could sustain. Since the chronicle/superfluid
 * re-homing to the mainnet fork, no Tier 2 suite targets Sepolia and CI
 * runs no Sepolia fork; the entry stays for the remaining Sepolia
 * testData (aave-v3) exercised by local Tier 1 sims
 * (scripts/protocol-local.sh sim sepolia).
 */
export const FORK_CHAIN_IDS: Set<string> = new Set([
  "1",
  "11155111",
  "8453",
  "42161",
]);

export type TokenSymbol =
  | "WETH"
  | "USDC"
  | "USDT"
  | "DAI"
  | "USDS"
  | "USDE"
  | "MKR"
  | "LINK"
  | "WSTETH"
  | "DAIX"
  | "SY_WSTETH"
  | "PT_WSTETH"
  | "YT_WSTETH";

export type TokenEntry = {
  address: string;
  decimals: number;
  symbol: TokenSymbol;
};

/**
 * Per-chain token address registry. Extend per protocol as new chains come online.
 */
export const TOKEN_REGISTRY: Record<
  string /* chainId */,
  Partial<Record<TokenSymbol, TokenEntry>>
> = {
  // Ethereum Mainnet (fork mode only — no testnet faucets)
  "1": {
    WETH: {
      address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
      decimals: 18,
      symbol: "WETH",
    },
    USDC: {
      address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      decimals: 6,
      symbol: "USDC",
    },
    WSTETH: {
      address: "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0",
      decimals: 18,
      symbol: "WSTETH",
    },
    USDS: {
      address: "0xdC035D45d973E3EC169d2276DDab16f1e407384F",
      decimals: 18,
      symbol: "USDS",
    },
    DAI: {
      address: "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      decimals: 18,
      symbol: "DAI",
    },
    // Ethena USDe stablecoin. No whale registered on purpose: acquired
    // via balances-slot fabrication (Solidity mapping slot 2, verified
    // against balanceOf on mainnet 2026-07-08).
    USDE: {
      address: "0x4c9EDD5852cd905f086C759E8383e09bff1E68B3",
      decimals: 18,
      symbol: "USDE",
    },
    // Maker MKR (DSToken). No whale registered on purpose: acquired via
    // balances-slot fabrication (Solidity mapping slot 1, verified
    // against balanceOf on mainnet 2026-07-08).
    MKR: {
      address: "0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2",
      decimals: 18,
      symbol: "MKR",
    },
    // Superfluid canonical Super DAI wrapper (resolved from the on-chain
    // Superfluid resolver key "supertokens.v1.DAIx", verified 2026-07-07).
    // Chosen over USDCx for the coverage fixtures: USDCx's upgrade() routes
    // the underlying into Sky savings, and its gas cost jumps between the
    // estimation block and the execution block (sUSDS drip), so
    // exact-estimate sends reliably run out of gas on an anvil fork. DAIx
    // is a plain escrow wrapper.
    DAIX: {
      address: "0x4F228bf911ed67730e4B51B1F82AC291B49053ee",
      decimals: 18,
      symbol: "DAIX",
    },
    // Pendle wstETH market tokens (market 0x3428...be3b, expiry
    // 2027-12-30). Resolved from the market's readTokens() and verified
    // 2026-07-08 via eth_call at the pinned fixture block 25487331
    // (code present, decimals 18 each). These bind pendle's pinned-block
    // fixtures; refresh together with the fixture in protocols/pendle.ts
    // (see specs/protocol-coverage-methodology.md).
    SY_WSTETH: {
      address: "0xcbC72d92b2dc8187414F6734718563898740C0BC",
      decimals: 18,
      symbol: "SY_WSTETH",
    },
    PT_WSTETH: {
      address: "0xb253Eff1104802b97aC7E3aC9FdD73AecE295a2c",
      decimals: 18,
      symbol: "PT_WSTETH",
    },
    YT_WSTETH: {
      address: "0x04B7Fa1e727d7290D6E24fA9b426d0c940283a95",
      decimals: 18,
      symbol: "YT_WSTETH",
    },
  },
  // Base Mainnet (used by ajna coverage tests; not fork-mode — no testnet faucets)
  "8453": {
    WETH: {
      address: "0x4200000000000000000000000000000000000006",
      decimals: 18,
      symbol: "WETH",
    },
    USDC: {
      address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
      decimals: 6,
      symbol: "USDC",
    },
  },
  // Arbitrum One (chainlink Tier 1 read sweep; not fork-mode — no faucets).
  // Present so the Event-trigger builder can resolve a contractAddress for
  // chain 42161 (pickEventContractAddress); chainlink's reads bind contracts
  // directly and reference no token symbol here.
  "42161": {
    WETH: {
      address: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1",
      decimals: 18,
      symbol: "WETH",
    },
    USDC: {
      address: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831",
      decimals: 6,
      symbol: "USDC",
    },
  },
  // Ethereum Sepolia
  "11155111": {
    // Aave V3 Sepolia DAI test token (matches existing
    // scripts/seed/workflows/aave-v3/write-actions.json usage).
    DAI: {
      address: "0xFF34B3d4Aee8ddCd6F9AFFFB6Fe49bD371b8a357",
      decimals: 18,
      symbol: "DAI",
    },
    // Sepolia WETH (canonical Sepolia WETH).
    WETH: {
      address: "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14",
      decimals: 18,
      symbol: "WETH",
    },
    // Aave V3 Sepolia LINK test token. Selected over DAI because Aave's
    // DAI/USDC/USDT reserves on Sepolia hit `SUPPLY_CAP_EXCEEDED` (error 51);
    // LINK has headroom and is borrowable. Verified 2026-05-12 via eth_call.
    LINK: {
      address: "0xf8Fb3713D459D7C1018BD0A49D19b4C44290EBE5",
      decimals: 18,
      symbol: "LINK",
    },
  },
};

/** Faucet contract that mints a testnet token to a recipient. */
export type FaucetSpec = {
  contract: string;
  functionName: string;
  /** Full ABI JSON for the mint function, single-element array. */
  abi: string;
};

/**
 * Faucet registry consumed by `tests/e2e/vitest/protocol-coverage/_shared/funding.ts`.
 * The TS preflight calls each faucet from the funder EOA before the setup
 * workflow runs. Args are bound by input *name* (case-insensitive):
 *   `token` -> token's address on this chain
 *   `to` / `recipient` -> the test wallet address
 *   `amount` / `value` -> requiredTokens[i].human in wei (using token decimals)
 *
 * Fork-mode chains (FORK_CHAIN_IDS) use whale impersonation instead of faucets.
 * Their entries here are intentionally absent; ensureErc20Acquired delegates to
 * ensureErc20OnFork before reaching the FAUCETS lookup.
 */
export const FAUCETS: Record<
  string /* chainId */,
  Partial<Record<TokenSymbol, FaucetSpec>>
> = {
  "11155111": {
    // Aave V3 Sepolia faucet: mints any Aave testnet reserve token.
    // Verified contract exists at this address (eth_getCode).
    LINK: {
      contract: "0xC959483DBa39aa9E78757139af0e9a2EDEb3f42D",
      functionName: "mint",
      abi: JSON.stringify([
        {
          type: "function",
          name: "mint",
          stateMutability: "nonpayable",
          inputs: [
            { name: "token", type: "address" },
            { name: "to", type: "address" },
            { name: "amount", type: "uint256" },
          ],
          outputs: [{ name: "", type: "uint256" }],
        },
      ]),
    },
  },
};

/**
 * Whale addresses for fork-mode ERC20 provisioning. On anvil mainnet forks,
 * ensureErc20OnFork impersonates the whale and transfers tokens to the test
 * wallet. Addresses are large protocol-held balances; verify via Etherscan
 * token-holder page before updating.
 */
export type WhaleSpec = {
  address: string;
};

export const FORK_WHALES: Record<
  string /* chainId */,
  Partial<Record<TokenSymbol, WhaleSpec>>
> = {
  "1": {
    // Lido stETH contract holds large wstETH balance (wrapping mechanism).
    WSTETH: { address: "0x0B925eD163218f6662a35e0f0371Ac234f9E9371" },
    // Circle's USDC reserve / bridge account holds large USDC balance.
    USDC: { address: "0x37305B1cD40574E4C5Ce33f8e8306Be057fD7341" },
    // No USDS entry: the PSM whale previously registered here
    // (0x3Ba23D309F6e88f0a9Ac0bEe797AfaCa93B78b78) held 0 USDS by
    // 2026-07-08, so USDS moved to balances-slot fabrication
    // (Solidity mapping slot 2 behind the proxy, verified against
    // balanceOf on mainnet 2026-07-08). See fabricate-state.ts.
    // MakerDAO MCD_JOIN_DAI: large DAI holder.
    DAI: { address: "0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643" },
    // The Pendle wstETH market itself: its LP reserve held ~1306 SY at
    // the pinned fixture block (balanceOf verified 2026-07-08).
    SY_WSTETH: { address: "0x34280882267ffa6383B363E278B027Be083bBe3b" },
  },
};

/**
 * Native gas floor below which the funder must top up the test wallet.
 * Sized to cover several write fixtures (typical Sepolia tx cost is
 * ~0.0012 ETH; coverage suites run multiple writes per CI run, sometimes
 * concurrently across protocols sharing one wallet via NonceManager).
 * Fork-mode chains get a generous floor since anvil_setBalance is free.
 *
 * Fork sizing note: the node validates gasLimit x maxFeePerGas against
 * the balance before submission, and forked chains inherit the live
 * base fee at fork time, so fork floors are set generously (cheatcode
 * balances are free).
 *
 * No entry for chain 8453 (Base): ajna is the only protocol-coverage suite
 * on it, every write action it has is marked skipped in TEST_DATA, and
 * runSetup() only calls ensureNativeGas when a chain actually has a
 * transaction to sign -- reads are free, so no real Base mainnet ETH is
 * ever required.
 */
export const MIN_NATIVE_BALANCE_WEI_BY_CHAIN: Record<string, bigint> = {
  "1": BigInt("1000000000000000000"), // 1 ETH (fork mode, free via anvil_setBalance)
  "11155111": BigInt("1000000000000000000"), // 1 ETH (fork mode, free via anvil_setBalance)
  "8453": BigInt("1000000000000000000"), // 1 ETH (Base fork, free via anvil_setBalance)
  "42161": BigInt("1000000000000000000"), // 1 ETH (Arbitrum fork, free via anvil_setBalance)
};

/**
 * How much native to send when topping up. Aim for ~25x the per-tx cost so
 * a single top-up survives a full suite run without re-checking mid-flight,
 * including a multi-tx setup sequence (e.g. superfluid: faucet mint +
 * approve + wrap in setup, then ~7 more writes in the coverage phase --
 * observed to need ~0.012-0.013 ETH total end to end) plus headroom for
 * concurrent NonceManager usage across protocols sharing one wallet.
 * Fork-mode: set once via anvil_setBalance to 10 ETH and never re-top-up.
 *
 * The TESTNET_FUNDER_PK EOA now matters only for live (non-fork) chains
 * with spendable requirements. Sepolia moved to fork mode (see
 * FORK_CHAIN_IDS) after live-testnet top-ups proved unsustainable: each
 * ephemeral CI run seeds a fresh Turnkey wallet, stranding every top-up,
 * and base-fee spikes priced single transactions above what the funder
 * (~0.16 ETH) could keep covering.
 */
export const FUND_NATIVE_AMOUNT_WEI_BY_CHAIN: Record<string, bigint> = {
  "1": BigInt("10000000000000000000"), // 10 ETH (fork mode)
  "11155111": BigInt("10000000000000000000"), // 10 ETH (fork mode)
  "8453": BigInt("10000000000000000000"), // 10 ETH (Base fork mode)
  "42161": BigInt("10000000000000000000"), // 10 ETH (Arbitrum fork mode)
};
