/**
 * Chain-scoped test data for protocol-coverage fixtures (KEEP-458).
 *
 * Authoritative for: known testnet tokens, faucet contracts, fork-mode whale
 * addresses. The persistent E2E test user's wallet address is NOT here --
 * KEEP-529 made it HSM-generated by Turnkey, so the address differs per
 * environment. Callers look it up from `organization_wallets` at test/seed
 * time and pass it into the builders in `lib/test-data/build-workflow.ts`.
 *
 * Where addresses come from:
 *   - Tokens are extracted/extended from `scripts/seed/seed-tokens.ts` and from
 *     existing usage in `tests/integration/protocol-superfluid-onchain.test.ts`.
 *   - Aave V3 Sepolia faucet is from Aave's address book (verify against
 *     https://aave.com/docs/resources/addresses before relying on it).
 *   - Mainnet whale addresses are large protocol-held balances verified via
 *     Etherscan token-holder rankings at the time of writing.
 */

/** Env var name the funder script reads. The PK itself must never appear in code. */
export const TESTNET_FUNDER_PK_ENV = "TESTNET_FUNDER_PK";

/**
 * Chain IDs where anvil fork-mode provisioning applies. On these chains
 * ensureNativeGas uses anvil_setBalance and ensureErc20Acquired uses whale
 * impersonation instead of a real funder EOA + testnet faucets.
 */
export const FORK_CHAIN_IDS: Set<string> = new Set(["1"]);

export type TokenSymbol =
  | "WETH"
  | "USDC"
  | "USDT"
  | "DAI"
  | "USDS"
  | "LINK"
  | "WSTETH"
  | "FUSDC"
  | "FUSDCX";

export type TokenEntry = {
  address: string;
  decimals: number;
  symbol: TokenSymbol;
};

/**
 * Per-chain token address registry. Extend per protocol as new chains come online.
 */
export const TOKEN_REGISTRY: Record<
  string /* chainId */,
  Partial<Record<TokenSymbol, TokenEntry>>
> = {
  // Ethereum Mainnet (fork mode only — no testnet faucets)
  "1": {
    WETH: {
      address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
      decimals: 18,
      symbol: "WETH",
    },
    USDC: {
      address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      decimals: 6,
      symbol: "USDC",
    },
    WSTETH: {
      address: "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0",
      decimals: 18,
      symbol: "WSTETH",
    },
  },
  // Ethereum Sepolia
  "11155111": {
    // Aave V3 Sepolia DAI test token (matches existing
    // scripts/seed/workflows/aave-v3/write-actions.json usage).
    DAI: {
      address: "0xFF34B3d4Aee8ddCd6F9AFFFB6Fe49bD371b8a357",
      decimals: 18,
      symbol: "DAI",
    },
    // Sepolia WETH (canonical Sepolia WETH).
    WETH: {
      address: "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14",
      decimals: 18,
      symbol: "WETH",
    },
    // Aave V3 Sepolia LINK test token. Selected over DAI because Aave's
    // DAI/USDC/USDT reserves on Sepolia hit `SUPPLY_CAP_EXCEEDED` (error 51);
    // LINK has headroom and is borrowable. Verified 2026-05-12 via eth_call.
    LINK: {
      address: "0xf8Fb3713D459D7C1018BD0A49D19b4C44290EBE5",
      decimals: 18,
      symbol: "LINK",
    },
    // Superfluid fUSDC underlying ERC-20 (from protocol-superfluid-onchain.test.ts:52).
    FUSDC: {
      address: "0xe72f289584eDA2bE69Cfe487f4638F09bAc920Db",
      decimals: 18,
      symbol: "FUSDC",
    },
    // Superfluid fUSDCx SuperToken wrapper (from protocol-superfluid-onchain.test.ts:49).
    FUSDCX: {
      address: "0xb598E6C621618a9f63788816ffb50Ee2862D443B",
      decimals: 18,
      symbol: "FUSDCX",
    },
  },
};

/** Faucet contract that mints a testnet token to a recipient. */
export type FaucetSpec = {
  contract: string;
  functionName: string;
  /** Full ABI JSON for the mint function, single-element array. */
  abi: string;
};

/**
 * Faucet registry consumed by `tests/e2e/vitest/protocol-coverage/_shared/funding.ts`.
 * The TS preflight calls each faucet from the funder EOA before the setup
 * workflow runs. Args are bound by input *name* (case-insensitive):
 *   `token` -> token's address on this chain
 *   `to` / `recipient` -> the test wallet address
 *   `amount` / `value` -> requiredTokens[i].human in wei (using token decimals)
 *
 * Fork-mode chains (FORK_CHAIN_IDS) use whale impersonation instead of faucets.
 * Their entries here are intentionally absent; ensureErc20Acquired delegates to
 * ensureErc20OnFork before reaching the FAUCETS lookup.
 */
export const FAUCETS: Record<
  string /* chainId */,
  Partial<Record<TokenSymbol, FaucetSpec>>
> = {
  "11155111": {
    // Aave V3 Sepolia faucet: mints any Aave testnet reserve token.
    // Verified contract exists at this address (eth_getCode).
    LINK: {
      contract: "0xC959483DBa39aa9E78757139af0e9a2EDEb3f42D",
      functionName: "mint",
      abi: JSON.stringify([
        {
          type: "function",
          name: "mint",
          stateMutability: "nonpayable",
          inputs: [
            { name: "token", type: "address" },
            { name: "to", type: "address" },
            { name: "amount", type: "uint256" },
          ],
          outputs: [{ name: "", type: "uint256" }],
        },
      ]),
    },
    // FUSDC exposes a permissionless `mint(to, amount)` on its own ERC20.
    // Verified by inspecting bytecode (selector 0x40c10f19 present).
    FUSDC: {
      contract: "0xe72f289584eDA2bE69Cfe487f4638F09bAc920Db",
      functionName: "mint",
      abi: JSON.stringify([
        {
          type: "function",
          name: "mint",
          stateMutability: "nonpayable",
          inputs: [
            { name: "to", type: "address" },
            { name: "amount", type: "uint256" },
          ],
          outputs: [],
        },
      ]),
    },
  },
};

/**
 * Whale addresses for fork-mode ERC20 provisioning. On anvil mainnet forks,
 * ensureErc20OnFork impersonates the whale and transfers tokens to the test
 * wallet. Addresses are large protocol-held balances; verify via Etherscan
 * token-holder page before updating.
 */
export type WhaleSpec = {
  address: string;
};

export const FORK_WHALES: Record<
  string /* chainId */,
  Partial<Record<TokenSymbol, WhaleSpec>>
> = {
  "1": {
    // Lido stETH contract holds large wstETH balance (wrapping mechanism).
    WSTETH: { address: "0x0B925eD163218f6662a35e0f0371Ac234f9E9371" },
    // Circle's USDC reserve / bridge account holds large USDC balance.
    USDC: { address: "0x37305B1cD40574E4C5Ce33f8e8306Be057fD7341" },
  },
};

/**
 * Native gas floor below which the funder must top up the test wallet.
 * Sized to cover several write fixtures (typical Sepolia tx cost is
 * ~0.0012 ETH; coverage suites run multiple writes per CI run, sometimes
 * concurrently across protocols sharing one wallet via NonceManager).
 * Fork-mode chains get a generous floor since anvil_setBalance is free.
 */
export const MIN_NATIVE_BALANCE_WEI_BY_CHAIN: Record<string, bigint> = {
  "1": BigInt("1000000000000000000"), // 1 ETH (fork mode, free via anvil_setBalance)
  "11155111": BigInt("10000000000000000"), // 0.01 ETH
};

/**
 * How much native to send when topping up. Aim for ~10x the per-tx cost so
 * a single top-up survives a full suite run without re-checking mid-flight.
 * Fork-mode: set once via anvil_setBalance to 10 ETH and never re-top-up.
 */
export const FUND_NATIVE_AMOUNT_WEI_BY_CHAIN: Record<string, bigint> = {
  "1": BigInt("10000000000000000000"), // 10 ETH (fork mode)
  "11155111": BigInt("20000000000000000"), // 0.02 ETH
};
