/**
 * Credential Fetcher
 *
 * SECURITY: Steps should fetch credentials at runtime using only an integration ID reference.
 * This ensures:
 * 1. Credentials are never passed as step parameters (not logged in observability)
 * 2. Credentials are reconstructed in secure, non-persisted contexts (in-memory only)
 * 3. Works for both production and test runs
 *
 * Pattern:
 * - Step input: { integrationId: "abc123", ...otherParams }  ← Safe to log
 * - Step fetches: credentials = await fetchCredentials(integrationId, principal)  ← Not logged
 * - Step uses: apiClient.call(credentials.apiKey)  ← In memory only
 * - Step returns: { result: data }  ← Safe to log (no credentials)
 */
import "server-only";

import { PLUGIN_CREDENTIAL_MAP } from "./credential-map";
import { buildDatabaseUrlFromConfig } from "./db/connection-utils";
import { getIntegrationById } from "./db/integrations";
import {
  filterUnauthorizedIntegrationIds,
  type IntegrationPrincipal,
} from "./integrations/authorization";
import type { IntegrationConfig, IntegrationType } from "./types/integration";

// WorkflowCredentials is now a generic record since plugins define their own keys
export type WorkflowCredentials = Record<string, string | undefined>;

// System integrations that don't have plugins need hardcoded mapping
const SYSTEM_CREDENTIAL_MAPPERS: Record<
  string,
  (config: IntegrationConfig) => WorkflowCredentials
> = {
  database: (config) => {
    const creds: WorkflowCredentials = {};
    const url = buildDatabaseUrlFromConfig(config);
    if (url) {
      creds.DATABASE_URL = url;
    }
    if (
      config.sslMode &&
      typeof config.sslMode === "string" &&
      ["require", "prefer", "disable", "auto"].includes(config.sslMode)
    ) {
      creds.DATABASE_SSL_MODE = config.sslMode;
    }
    return creds;
  },
};

/**
 * Map integration config to WorkflowCredentials format.
 *
 * Uses the build-time PLUGIN_CREDENTIAL_MAP (generated by
 * scripts/discover-plugins.ts) so this works inside Workflow DevKit step
 * bundles where the runtime plugin registry is unreachable. Hardcoded
 * mappers handle system integrations that don't have a plugin (e.g. database).
 */
function mapIntegrationConfig(
  integrationType: IntegrationType,
  config: IntegrationConfig
): WorkflowCredentials {
  const systemMapper = SYSTEM_CREDENTIAL_MAPPERS[integrationType];
  if (systemMapper) {
    return systemMapper(config);
  }

  const fieldMap = PLUGIN_CREDENTIAL_MAP[integrationType];
  if (!fieldMap) {
    return {};
  }

  const creds: WorkflowCredentials = {};
  for (const [configKey, envVar] of Object.entries(fieldMap)) {
    const value = config[configKey];
    if (value !== undefined && value !== null) {
      creds[envVar] = String(value);
    }
  }
  return creds;
}

/**
 * Fetch credentials for an integration by ID.
 *
 * The fetch is authorized against `principal` (organization visibility /
 * specific_members grant) before any credential is decrypted, returning no
 * credentials if the principal is not authorized. This is the runtime guard
 * that stops a step from resolving a connection belonging to another org if a
 * referenced id ever escapes the pre-execution / save-time checks. `principal`
 * is required so every step fails closed; steps source it from
 * `input._context` (the run's owner context).
 *
 * @param integrationId - The ID of the integration to fetch credentials for
 * @param principal - Owner-context principal to authorize against
 * @returns WorkflowCredentials object with the integration's credentials
 */
export async function fetchCredentials(
  integrationId: string,
  principal: IntegrationPrincipal
): Promise<WorkflowCredentials> {
  // A node with no integration selected passes undefined at runtime; treat it
  // as a missing integration instead of letting getIntegrationById(undefined)
  // throw UNDEFINED_VALUE and surface as a system error.
  if (!integrationId) {
    return {};
  }

  const unauthorized = await filterUnauthorizedIntegrationIds(
    [integrationId],
    principal
  );
  if (unauthorized.length > 0) {
    return {};
  }

  const integration = await getIntegrationById(integrationId);
  if (!integration) {
    return {};
  }
  return mapIntegrationConfig(integration.type, integration.config);
}

/**
 * Legacy function name for backward compatibility
 * Now fetches by integration ID instead of workflow ID
 */
export function fetchIntegrationCredentials(
  integrationId: string,
  principal: IntegrationPrincipal
): Promise<WorkflowCredentials> {
  return fetchCredentials(integrationId, principal);
}
