/**
 * Credential Map (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * Maps each integration type to its formField configKey -> envVar mapping.
 * Used by lib/credential-fetcher.ts so that the credential keys exposed to
 * step files (e.g. credentials.TELEGRAM_BOT_TOKEN) can be resolved even when
 * the runtime plugin registry is unavailable - notably inside Workflow DevKit
 * step bundles, where the plugin registry import chain is not pulled in.
 *
 * Generated entries: 35 plugin(s), 10 field(s)
 */

import "server-only";

export const PLUGIN_CREDENTIAL_MAP: Record<
  string,
  Record<string, string>
> = {
  "safe": {
    "apiKey": "apiKey",
  },
  "blockscout": {
    "apiUrl": "BLOCKSCOUT_API_URL",
    "apiKey": "BLOCKSCOUT_API_KEY",
  },
  "discord": {
    "webhookUrl": "webhookUrl",
  },
  "elizaos": {
    "endpointUrl": "ELIZAOS_ENDPOINT_URL",
    "apiKey": "ELIZAOS_API_KEY",
    "agentId": "ELIZAOS_AGENT_ID",
  },
  "evm-chain": {
    "EVM_CHAIN_RPC_URL": "EVM_CHAIN_RPC_URL",
    "EVM_CHAIN_NAME": "EVM_CHAIN_NAME",
  },
  "sendgrid": {
    "apiKey": "SENDGRID_API_KEY",
  },
  "slack": {
    "apiKey": "SLACK_API_KEY",
  },
  "telegram": {
    "botToken": "TELEGRAM_BOT_TOKEN",
  },
};
