/**
 * Step Registry (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * This registry enables dynamic step imports that are statically analyzable
 * by the bundler. Each action type maps to its step importer function.
 *
 * Generated entries: 447
 */

import "server-only";

// biome-ignore lint/suspicious/noExplicitAny: Dynamic step module types - step functions take any input
export type StepFunction = (input: any) => Promise<any>;

// Step modules may contain the step function plus other exports (types, constants, etc.)
// biome-ignore lint/suspicious/noExplicitAny: Dynamic module with mixed exports
export type StepModule = Record<string, any>;

export type StepImporter = {
  importer: () => Promise<StepModule>;
  stepFunction: string;
};

/**
 * Plugin step importers - maps action types to their step import functions
 * These imports are statically analyzable by the bundler
 */
export const PLUGIN_STEP_IMPORTERS: Record<string, StepImporter> = {
  "aave-v3/supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aave-v3/withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aave-v3/borrow": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aave-v3/repay": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aave-v3/set-collateral": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aave-v3/get-user-account-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aave-v3/get-user-reserve-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aave-v4/supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aave-v4/withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aave-v4/borrow": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aave-v4/repay": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aave-v4/set-collateral": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aave-v4/get-reserve-id": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aave-v4/get-user-supplied-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aave-v4/get-user-debt": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aave-v4/get-user-account-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aerodrome/get-reserves": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aerodrome/get-pool-for-pair": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aerodrome/swap-exact-tokens": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aerodrome/add-liquidity": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aerodrome/remove-liquidity": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aerodrome/get-total-weight": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aerodrome/is-gauge-alive": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aerodrome/get-gauge-for-pool": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aerodrome/vote": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aerodrome/reset-votes": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aerodrome/claim-rewards": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aerodrome/get-all-pools-length": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aerodrome/get-venft-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aerodrome/get-lock-details": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aerodrome/create-lock": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aerodrome/increase-lock-amount": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aerodrome/increase-lock-duration": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aerodrome/withdraw-lock": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "aerodrome/get-amount-out": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aerodrome/aero-balance-of": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "aerodrome/aero-approve": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/get-auction-status": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/get-hpb-index": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/get-pool-lup": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/get-pool-htp": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/get-borrower-info": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/price-to-index": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/index-to-price": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/pool1-kicker-info": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/pool1-auction-info": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/pool1-bucket-info": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/pool1-inflator-info": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/pool1-kick": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/pool1-bucket-take": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/pool1-settle": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/pool1-withdraw-bonds": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/pool1-update-interest": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/pool1-deposit-index": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/pool2-kicker-info": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/pool2-auction-info": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/pool2-bucket-info": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/pool2-inflator-info": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/pool2-kick": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/pool2-bucket-take": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/pool2-settle": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/pool2-withdraw-bonds": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/pool2-update-interest": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/pool2-deposit-index": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault1-is-paused": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault1-get-buckets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault1-total-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault1-lp-to-value": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault1-drain": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/vault1-move": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/vault1-move-from-buffer": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/vault1-move-to-buffer": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/vault2-is-paused": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault2-get-buckets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault2-total-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault2-lp-to-value": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault2-drain": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/vault2-move": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/vault2-move-from-buffer": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/vault2-move-to-buffer": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ajna/vault1-buffer-ratio": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault1-min-bucket-index": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault2-buffer-ratio": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault2-min-bucket-index": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault1-buffer-total": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ajna/vault2-buffer-total": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/ccip-get-fee": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/ccip-send": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "chainlink/ccip-bnm-drip": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "chainlink/ccip-approve-bridge-token": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "chainlink/ccip-check-bridge-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/ccip-check-bridge-allowance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/ccip-approve-fee-token": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "chainlink/ccip-check-fee-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/ccip-check-fee-allowance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/eth-usd-latest-round-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/eth-usd-decimals": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/btc-usd-latest-round-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/btc-usd-decimals": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/link-usd-latest-round-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/link-usd-decimals": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/usdc-usd-latest-round-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/usdc-usd-decimals": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/dai-usd-latest-round-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/dai-usd-decimals": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/usdt-usd-latest-round-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/usdt-usd-decimals": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/link-eth-latest-round-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/link-eth-decimals": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/btc-eth-latest-round-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/btc-eth-decimals": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/latest-round-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/get-round-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/latest-answer": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/decimals": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/description": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chainlink/version": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/eth-usd-read": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/eth-usd-read-with-age": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/btc-usd-read": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/btc-usd-read-with-age": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/dai-usd-read": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/dai-usd-read-with-age": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/usdc-usd-read": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/usdc-usd-read-with-age": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/usdt-usd-read": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/usdt-usd-read-with-age": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/link-usd-read": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/link-usd-read-with-age": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/read": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/try-read": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/read-with-age": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/try-read-with-age": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "chronicle/self-kiss": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "compound/supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "compound/withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "compound/get-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "compound/get-collateral-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "compound/get-borrow-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "compound/get-utilization": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "compound/get-supply-rate": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "compound/get-borrow-rate": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "compound/get-total-supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "compound/get-total-borrow": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "compound/is-liquidatable": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "compound/get-num-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "cowswap/get-domain-separator": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "cowswap/get-vault-relayer": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "cowswap/get-filled-amount": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "cowswap/get-pre-signature": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "cowswap/set-pre-signature": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "cowswap/invalidate-order": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "cowswap/check-single-order": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "cowswap/get-cabinet": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "cowswap/remove-conditional-order": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "cowswap/create-conditional-order": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "curve/get-dy": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "curve/get-virtual-price": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "curve/get-coin": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "curve/get-pool-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "curve/calc-withdraw-one-coin": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "curve/exchange": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "curve/remove-liquidity-one-coin": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "curve/crv-balance-of": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "curve/crv-approve": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "curve/crv-transfer": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ethena/vault-asset": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-total-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-total-supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-convert-to-shares": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-convert-to-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-max-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-preview-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ethena/vault-max-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-preview-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ethena/vault-max-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-preview-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ethena/vault-max-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-preview-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/vault-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ethena/cooldown-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ethena/cooldown-shares": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ethena/get-cooldown-duration": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/get-cooldown-status": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/unstake": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ethena/get-usde-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "ethena/approve-usde": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "ethena/get-ena-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "frax-ether-v2/mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "frax-ether-v2/mint-and-give": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "frax-ether-v2/mint-and-stake": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "frax-ether-v2/mint-paused": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "hyperliquid/clearinghouse-state": {
    importer: () => import("@/plugins/hyperliquid/steps/clearinghouse-state"),
    stepFunction: "clearinghouseStateStep",
  },
  "hyperliquid/vault-details": {
    importer: () => import("@/plugins/hyperliquid/steps/vault-details"),
    stepFunction: "vaultDetailsStep",
  },
  "hyperliquid/validator-summaries": {
    importer: () => import("@/plugins/hyperliquid/steps/validator-summaries"),
    stepFunction: "validatorSummariesStep",
  },
  "hyperliquid/funding-history": {
    importer: () => import("@/plugins/hyperliquid/steps/funding-history"),
    stepFunction: "fundingHistoryStep",
  },
  "hyperliquid/spot-deploy-state": {
    importer: () => import("@/plugins/hyperliquid/steps/spot-deploy-state"),
    stepFunction: "spotDeployStateStep",
  },
  "hyperliquid/referral": {
    importer: () => import("@/plugins/hyperliquid/steps/referral"),
    stepFunction: "referralStep",
  },
  "hyperliquid/sub-accounts": {
    importer: () => import("@/plugins/hyperliquid/steps/sub-accounts"),
    stepFunction: "subAccountsStep",
  },
  "hyperliquid/active-asset-data": {
    importer: () => import("@/plugins/hyperliquid/steps/active-asset-data"),
    stepFunction: "activeAssetDataStep",
  },
  "lido/wrap": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "lido/unwrap": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "lido/get-steth-by-wsteth": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "lido/get-wsteth-by-steth": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "lido/steth-per-token": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "lido/tokens-per-steth": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "lido/get-wsteth-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "lido/get-wsteth-total-supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "lido/get-steth-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "lido/approve-steth": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/get-position": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/get-market": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/get-market-params": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/is-authorized": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/set-authorization": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/flash-loan": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/supply-collateral": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/borrow": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/repay": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/withdraw-collateral": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/liquidate": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/accrue-interest": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/vault-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/vault-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/vault-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/vault-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "morpho/vault-asset": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/vault-total-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/vault-total-supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/vault-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/vault-convert-to-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/vault-convert-to-shares": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/vault-preview-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/vault-preview-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/vault-preview-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/vault-preview-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/vault-max-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/vault-max-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/vault-max-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "morpho/vault-max-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "pendle/mint-py-from-sy": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "pendle/redeem-py-to-sy": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "pendle/get-ve-pendle-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "pendle/get-ve-pendle-total-supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "pendle/get-ve-pendle-position": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "pendle/get-market-expiry": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "pendle/is-market-expired": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "pendle/get-lp-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "pendle/get-active-lp-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "pendle/get-pt-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "pendle/is-pt-expired": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "pendle/get-yt-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "pendle/get-sy-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "pendle/get-sy-exchange-rate": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "robinhood/get-stock-price": {
    importer: () => import("@/plugins/robinhood/steps/get-stock-price"),
    stepFunction: "getStockPriceStep",
  },
  "robinhood/get-stock-position": {
    importer: () => import("@/plugins/robinhood/steps/get-stock-position"),
    stepFunction: "getStockPositionStep",
  },
  "robinhood/trade-stock-token": {
    importer: () => import("@/plugins/robinhood/steps/trade-stock-token"),
    stepFunction: "tradeStockTokenStep",
  },
  "robinhood/stock-market-status": {
    importer: () => import("@/plugins/robinhood/steps/stock-market-status"),
    stepFunction: "stockMarketStatusStep",
  },
  "rocket-pool/get-exchange-rate": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "rocket-pool/balance-of": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "rocket-pool/total-supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "rocket-pool/get-total-collateral": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "rocket-pool/burn": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "rocket-pool/deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "safe/get-owners": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "safe-wallet/get-owners": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "safe/get-threshold": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "safe-wallet/get-threshold": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "safe/is-owner": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "safe-wallet/is-owner": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "safe/get-nonce": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "safe-wallet/get-nonce": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "safe/is-module-enabled": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "safe-wallet/is-module-enabled": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "safe/get-modules-paginated": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "safe-wallet/get-modules-paginated": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "safe/get-pending-transactions": {
    importer: () => import("@/plugins/safe/steps/get-pending-transactions"),
    stepFunction: "getPendingTransactionsStep",
  },
  "safe-wallet/get-pending-transactions": {
    importer: () => import("@/plugins/safe/steps/get-pending-transactions"),
    stepFunction: "getPendingTransactionsStep",
  },
  "sky/vault-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "sky/vault-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "sky/vault-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "sky/vault-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "sky/vault-asset": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/vault-total-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/vault-total-supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/vault-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/vault-convert-to-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/vault-convert-to-shares": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/vault-preview-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/vault-preview-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/vault-preview-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/vault-preview-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/vault-max-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/vault-max-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/vault-max-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/vault-max-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "sky/st-usds-vault-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "sky/st-usds-vault-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "sky/st-usds-vault-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "sky/st-usds-vault-asset": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-total-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-total-supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-convert-to-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-convert-to-shares": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-preview-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-preview-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-preview-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-preview-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-max-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-max-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-max-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/st-usds-vault-max-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/get-usds-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/approve-usds": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "sky/get-dai-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/approve-dai": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "sky/get-sky-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "sky/convert-dai-to-usds": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "sky/convert-usds-to-dai": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "sky/convert-mkr-to-sky": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "spark/supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "spark/withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "spark/borrow": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "spark/repay": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "spark/set-collateral": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "spark/get-user-account-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/get-user-reserve-data": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "spark/vault-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "spark/vault-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "spark/vault-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "spark/vault-asset": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-total-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-total-supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-convert-to-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-convert-to-shares": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-preview-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-preview-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-preview-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-preview-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-max-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-max-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-max-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "spark/vault-max-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "superfluid/create-flow": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "superfluid/update-flow": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "superfluid/delete-flow": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "superfluid/get-flow": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "superfluid/get-cfa-net-flow": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "superfluid/grant-flow-operator": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "superfluid/create-pool": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "superfluid/update-member-units": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "superfluid/distribute": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "superfluid/distribute-flow": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "superfluid/connect-pool": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "superfluid/get-net-flow": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "superfluid/wrap": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "superfluid/unwrap": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "superfluid/get-super-token-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "superfluid/get-underlying-token": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "uniswap/get-pool": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "uniswap/get-position": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "uniswap/balance-of": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "uniswap/owner-of": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "uniswap/approve-position": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "uniswap/transfer-position": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "uniswap/burn-position": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "uniswap/swap-exact-input": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "uniswap/swap-exact-output": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "uniswap/quote-exact-input": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "uniswap/quote-exact-output": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "wrapped/wrap": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "wrapped/unwrap": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "wrapped/balance-of": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "yearn/vault-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "yearn/vault-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "yearn/vault-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-write"),
    stepFunction: "protocolWriteStep",
  },
  "yearn/vault-asset": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-total-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-total-supply": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-balance": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-convert-to-assets": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-convert-to-shares": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-preview-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-preview-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-preview-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-preview-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-max-deposit": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-max-mint": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-max-withdraw": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/vault-max-redeem": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/get-price-per-share": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/get-total-idle": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/get-total-debt": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/get-is-shutdown": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/get-api-version": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/get-profit-max-unlock-time": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/get-full-profit-unlock-date": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/get-accountant": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/get-deposit-limit": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/get-role-manager": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/get-use-default-queue": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/get-minimum-total-idle": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "yearn/get-vault-decimals": {
    importer: () => import("@/plugins/protocol/steps/protocol-read"),
    stepFunction: "protocolReadStep",
  },
  "blockscout/get-address-balance": {
    importer: () => import("@/plugins/blockscout/steps/get-address-balance"),
    stepFunction: "getAddressBalanceStep",
  },
  "blockscout/get-address-info": {
    importer: () => import("@/plugins/blockscout/steps/get-address-info"),
    stepFunction: "getAddressInfoStep",
  },
  "blockscout/get-address-counters": {
    importer: () => import("@/plugins/blockscout/steps/get-address-counters"),
    stepFunction: "getAddressCountersStep",
  },
  "blockscout/get-transaction": {
    importer: () => import("@/plugins/blockscout/steps/get-transaction"),
    stepFunction: "getTransactionStep",
  },
  "blockscout/get-token-info": {
    importer: () => import("@/plugins/blockscout/steps/get-token-info"),
    stepFunction: "getTokenInfoStep",
  },
  "code/run-code": {
    importer: () => import("@/plugins/code/steps/run-code"),
    stepFunction: "runCodeStep",
  },
  "discord/send-message": {
    importer: () => import("@/plugins/discord/steps/send-message"),
    stepFunction: "sendDiscordMessageStep",
  },
  "elizaos/execute-agent-action": {
    importer: () => import("@/plugins/elizaos/steps/execute-agent-action"),
    stepFunction: "executeAgentActionStep",
  },
  "evm-chain/chain-info": {
    importer: () => import("@/plugins/evm-chain/steps/chain-info"),
    stepFunction: "chainInfoStep",
  },
  "evm-chain/eth-balance": {
    importer: () => import("@/plugins/evm-chain/steps/eth-balance"),
    stepFunction: "ethBalanceStep",
  },
  "evm-chain/erc20-balance": {
    importer: () => import("@/plugins/evm-chain/steps/erc20-balance"),
    stepFunction: "erc20BalanceStep",
  },
  "evm-chain/gas-price": {
    importer: () => import("@/plugins/evm-chain/steps/gas-price"),
    stepFunction: "gasPriceStep",
  },
  "math/aggregate": {
    importer: () => import("@/plugins/math/steps/aggregate"),
    stepFunction: "aggregateStep",
  },
  "sendgrid/send-email": {
    importer: () => import("@/plugins/sendgrid/steps/send-email"),
    stepFunction: "sendEmailStep",
  },
  "slack/send-message": {
    importer: () => import("@/plugins/slack/steps/send-slack-message"),
    stepFunction: "sendSlackMessageStep",
  },
  "Send Slack Message": {
    importer: () => import("@/plugins/slack/steps/send-slack-message"),
    stepFunction: "sendSlackMessageStep",
  },
  "telegram/send-message": {
    importer: () => import("@/plugins/telegram/steps/send-message"),
    stepFunction: "sendTelegramMessageStep",
  },
  "tempo/transfer-with-memo": {
    importer: () => import("@/plugins/tempo/steps/transfer-with-memo"),
    stepFunction: "transferWithMemoStep",
  },
  "tempo/batch-payout": {
    importer: () => import("@/plugins/tempo/steps/batch-payout"),
    stepFunction: "batchPayoutStep",
  },
  "tempo/dex-swap": {
    importer: () => import("@/plugins/tempo/steps/dex-swap"),
    stepFunction: "dexSwapStep",
  },
  "tempo/hold-payment": {
    importer: () => import("@/plugins/tempo/steps/hold-payment"),
    stepFunction: "holdPaymentStep",
  },
  "web3/check-balance": {
    importer: () => import("@/plugins/web3/steps/check-balance"),
    stepFunction: "checkBalanceStep",
  },
  "Check Balance": {
    importer: () => import("@/plugins/web3/steps/check-balance"),
    stepFunction: "checkBalanceStep",
  },
  "web3/check-token-balance": {
    importer: () => import("@/plugins/web3/steps/check-token-balance"),
    stepFunction: "checkTokenBalanceStep",
  },
  "web3/get-spl-token-balance": {
    importer: () => import("@/plugins/web3/steps/get-spl-token-balance"),
    stepFunction: "getSplTokenBalanceStep",
  },
  "web3/transfer-funds": {
    importer: () => import("@/plugins/web3/steps/transfer-funds"),
    stepFunction: "transferFundsStep",
  },
  "Transfer Funds": {
    importer: () => import("@/plugins/web3/steps/transfer-funds"),
    stepFunction: "transferFundsStep",
  },
  "web3/transfer-token": {
    importer: () => import("@/plugins/web3/steps/transfer-token"),
    stepFunction: "transferTokenStep",
  },
  "web3/transfer-spl-token": {
    importer: () => import("@/plugins/web3/steps/transfer-spl-token"),
    stepFunction: "transferSplTokenStep",
  },
  "web3/send-raw-solana-instruction": {
    importer: () => import("@/plugins/web3/steps/send-raw-solana-instruction"),
    stepFunction: "sendRawSolanaInstructionStep",
  },
  "web3/call-solana-program-anchor": {
    importer: () => import("@/plugins/web3/steps/call-solana-program"),
    stepFunction: "callSolanaProgramStep",
  },
  "web3/read-solana-account": {
    importer: () => import("@/plugins/web3/steps/read-solana-account"),
    stepFunction: "readSolanaAccountStep",
  },
  "web3/read-solana-program-anchor": {
    importer: () => import("@/plugins/web3/steps/read-solana-program"),
    stepFunction: "readSolanaProgramStep",
  },
  "web3/query-solana-program-events": {
    importer: () => import("@/plugins/web3/steps/query-solana-program-events"),
    stepFunction: "querySolanaProgramEventsStep",
  },
  "web3/read-contract": {
    importer: () => import("@/plugins/web3/steps/read-contract"),
    stepFunction: "readContractStep",
  },
  "Read Contract": {
    importer: () => import("@/plugins/web3/steps/read-contract"),
    stepFunction: "readContractStep",
  },
  "web3/get-transaction": {
    importer: () => import("@/plugins/web3/steps/get-transaction"),
    stepFunction: "getTransactionStep",
  },
  "web3/decode-calldata": {
    importer: () => import("@/plugins/web3/steps/decode-calldata"),
    stepFunction: "decodeCalldataStep",
  },
  "web3/assess-risk": {
    importer: () => import("@/plugins/web3/steps/assess-risk"),
    stepFunction: "assessRiskStep",
  },
  "web3/query-events": {
    importer: () => import("@/plugins/web3/steps/query-events"),
    stepFunction: "queryEventsStep",
  },
  "web3/query-transactions": {
    importer: () => import("@/plugins/web3/steps/query-transactions"),
    stepFunction: "queryTransactionsStep",
  },
  "web3/batch-read-contract": {
    importer: () => import("@/plugins/web3/steps/batch-read-contract"),
    stepFunction: "batchReadContractStep",
  },
  "web3/batch-write-contract": {
    importer: () => import("@/plugins/web3/steps/batch-write-contract"),
    stepFunction: "batchWriteContractStep",
  },
  "web3/approve-token": {
    importer: () => import("@/plugins/web3/steps/approve-token"),
    stepFunction: "approveTokenStep",
  },
  "web3/check-allowance": {
    importer: () => import("@/plugins/web3/steps/check-allowance"),
    stepFunction: "checkAllowanceStep",
  },
  "web3/write-contract": {
    importer: () => import("@/plugins/web3/steps/write-contract"),
    stepFunction: "writeContractStep",
  },
  "Write Contract": {
    importer: () => import("@/plugins/web3/steps/write-contract"),
    stepFunction: "writeContractStep",
  },
  "web3/sign-typed-data": {
    importer: () => import("@/plugins/web3/steps/sign-typed-data"),
    stepFunction: "signTypedDataStep",
  },
  "webhook/send-webhook": {
    importer: () => import("@/plugins/webhook/steps/send-webhook"),
    stepFunction: "sendWebhookStep",
  },
};

/**
 * Action labels - maps action IDs to human-readable labels
 * Used for displaying friendly names in the UI (e.g., Runs tab)
 */
export const ACTION_LABELS: Record<string, string> = {
  "aave-v3/supply": "Aave V3: Supply Asset",
  "aave-v3/withdraw": "Aave V3: Withdraw Asset",
  "aave-v3/borrow": "Aave V3: Borrow Asset",
  "aave-v3/repay": "Aave V3: Repay Debt",
  "aave-v3/set-collateral": "Aave V3: Set Asset as Collateral",
  "aave-v3/get-user-account-data": "Aave V3: Get User Account Data",
  "aave-v3/get-user-reserve-data": "Aave V3: Get User Reserve Data",
  "aave-v4/supply": "Aave V4: Supply Asset",
  "aave-v4/withdraw": "Aave V4: Withdraw Asset",
  "aave-v4/borrow": "Aave V4: Borrow Asset",
  "aave-v4/repay": "Aave V4: Repay Debt",
  "aave-v4/set-collateral": "Aave V4: Set Asset as Collateral",
  "aave-v4/get-reserve-id": "Aave V4: Get Reserve ID",
  "aave-v4/get-user-supplied-assets": "Aave V4: Get User Supplied Assets",
  "aave-v4/get-user-debt": "Aave V4: Get User Debt",
  "aave-v4/get-user-account-data": "Aave V4: Get User Account Data",
  "aerodrome/get-reserves": "Aerodrome: Get Pool Reserves",
  "aerodrome/get-pool-for-pair": "Aerodrome: Get Pool Address",
  "aerodrome/swap-exact-tokens": "Aerodrome: Swap Exact Tokens",
  "aerodrome/add-liquidity": "Aerodrome: Add Liquidity",
  "aerodrome/remove-liquidity": "Aerodrome: Remove Liquidity",
  "aerodrome/get-total-weight": "Aerodrome: Get Total Voting Weight",
  "aerodrome/is-gauge-alive": "Aerodrome: Check Gauge Status",
  "aerodrome/get-gauge-for-pool": "Aerodrome: Get Gauge for Pool",
  "aerodrome/vote": "Aerodrome: Vote on Gauges",
  "aerodrome/reset-votes": "Aerodrome: Reset Votes",
  "aerodrome/claim-rewards": "Aerodrome: Claim Gauge Rewards",
  "aerodrome/get-all-pools-length": "Aerodrome: Get Total Pool Count",
  "aerodrome/get-venft-balance": "Aerodrome: Get veNFT Voting Power",
  "aerodrome/get-lock-details": "Aerodrome: Get Lock Details",
  "aerodrome/create-lock": "Aerodrome: Create veAERO Lock",
  "aerodrome/increase-lock-amount": "Aerodrome: Increase Lock Amount",
  "aerodrome/increase-lock-duration": "Aerodrome: Increase Lock Duration",
  "aerodrome/withdraw-lock": "Aerodrome: Withdraw Expired Lock",
  "aerodrome/get-amount-out": "Aerodrome: Get Expected Output",
  "aerodrome/aero-balance-of": "Aerodrome: Get AERO Balance",
  "aerodrome/aero-approve": "Aerodrome: Approve AERO",
  "ajna/get-auction-status": "Ajna: Get Auction Status",
  "ajna/get-hpb-index": "Ajna: Get HPB Index",
  "ajna/get-pool-lup": "Ajna: Get Pool LUP",
  "ajna/get-pool-htp": "Ajna: Get Pool HTP",
  "ajna/get-borrower-info": "Ajna: Get Borrower Info",
  "ajna/price-to-index": "Ajna: Price to Bucket Index",
  "ajna/index-to-price": "Ajna: Bucket Index to Price",
  "ajna/pool1-kicker-info": "Ajna: cbBTC/usBTCd Kicker Info",
  "ajna/pool1-auction-info": "Ajna: cbBTC/usBTCd Auction Info",
  "ajna/pool1-bucket-info": "Ajna: cbBTC/usBTCd Bucket Info",
  "ajna/pool1-inflator-info": "Ajna: cbBTC/usBTCd Inflator Info",
  "ajna/pool1-kick": "Ajna: cbBTC/usBTCd Kick",
  "ajna/pool1-bucket-take": "Ajna: cbBTC/usBTCd Bucket Take",
  "ajna/pool1-settle": "Ajna: cbBTC/usBTCd Settle",
  "ajna/pool1-withdraw-bonds": "Ajna: cbBTC/usBTCd Withdraw Bonds",
  "ajna/pool1-update-interest": "Ajna: cbBTC/usBTCd Update Interest",
  "ajna/pool1-deposit-index": "Ajna: cbBTC/usBTCd Deposit Index",
  "ajna/pool2-kicker-info": "Ajna: usBTCd/webmx Kicker Info",
  "ajna/pool2-auction-info": "Ajna: usBTCd/webmx Auction Info",
  "ajna/pool2-bucket-info": "Ajna: usBTCd/webmx Bucket Info",
  "ajna/pool2-inflator-info": "Ajna: usBTCd/webmx Inflator Info",
  "ajna/pool2-kick": "Ajna: usBTCd/webmx Kick",
  "ajna/pool2-bucket-take": "Ajna: usBTCd/webmx Bucket Take",
  "ajna/pool2-settle": "Ajna: usBTCd/webmx Settle",
  "ajna/pool2-withdraw-bonds": "Ajna: usBTCd/webmx Withdraw Bonds",
  "ajna/pool2-update-interest": "Ajna: usBTCd/webmx Update Interest",
  "ajna/pool2-deposit-index": "Ajna: usBTCd/webmx Deposit Index",
  "ajna/vault1-is-paused": "Ajna: cbBTC/usBTCd Is Paused",
  "ajna/vault1-get-buckets": "Ajna: cbBTC/usBTCd Get Buckets",
  "ajna/vault1-total-assets": "Ajna: cbBTC/usBTCd Total Assets",
  "ajna/vault1-lp-to-value": "Ajna: cbBTC/usBTCd LP to Value",
  "ajna/vault1-drain": "Ajna: cbBTC/usBTCd Drain Bucket",
  "ajna/vault1-move": "Ajna: cbBTC/usBTCd Move Liquidity",
  "ajna/vault1-move-from-buffer": "Ajna: cbBTC/usBTCd Move From Buffer",
  "ajna/vault1-move-to-buffer": "Ajna: cbBTC/usBTCd Move To Buffer",
  "ajna/vault2-is-paused": "Ajna: usBTCd/webmx Is Paused",
  "ajna/vault2-get-buckets": "Ajna: usBTCd/webmx Get Buckets",
  "ajna/vault2-total-assets": "Ajna: usBTCd/webmx Total Assets",
  "ajna/vault2-lp-to-value": "Ajna: usBTCd/webmx LP to Value",
  "ajna/vault2-drain": "Ajna: usBTCd/webmx Drain Bucket",
  "ajna/vault2-move": "Ajna: usBTCd/webmx Move Liquidity",
  "ajna/vault2-move-from-buffer": "Ajna: usBTCd/webmx Move From Buffer",
  "ajna/vault2-move-to-buffer": "Ajna: usBTCd/webmx Move To Buffer",
  "ajna/vault1-buffer-ratio": "Ajna: cbBTC/usBTCd Buffer Ratio",
  "ajna/vault1-min-bucket-index": "Ajna: cbBTC/usBTCd Min Bucket Index",
  "ajna/vault2-buffer-ratio": "Ajna: usBTCd/webmx Buffer Ratio",
  "ajna/vault2-min-bucket-index": "Ajna: usBTCd/webmx Min Bucket Index",
  "ajna/vault1-buffer-total": "Ajna: cbBTC/usBTCd Buffer Total",
  "ajna/vault2-buffer-total": "Ajna: usBTCd/webmx Buffer Total",
  "chainlink/ccip-get-fee": "Chainlink: CCIP Get Fee",
  "chainlink/ccip-send": "Chainlink: CCIP Send",
  "chainlink/ccip-bnm-drip": "Chainlink: CCIP-BnM Drip (Testnet)",
  "chainlink/ccip-approve-bridge-token": "Chainlink: CCIP Approve Bridge Token",
  "chainlink/ccip-check-bridge-balance": "Chainlink: CCIP Check Bridge Token Balance",
  "chainlink/ccip-check-bridge-allowance": "Chainlink: CCIP Check Bridge Token Allowance",
  "chainlink/ccip-approve-fee-token": "Chainlink: CCIP Approve Fee Token",
  "chainlink/ccip-check-fee-balance": "Chainlink: CCIP Check Fee Token Balance",
  "chainlink/ccip-check-fee-allowance": "Chainlink: CCIP Check Fee Token Allowance",
  "chainlink/eth-usd-latest-round-data": "Chainlink: Get ETH/USD Latest Round Data",
  "chainlink/eth-usd-decimals": "Chainlink: Get ETH/USD Decimals",
  "chainlink/btc-usd-latest-round-data": "Chainlink: Get BTC/USD Latest Round Data",
  "chainlink/btc-usd-decimals": "Chainlink: Get BTC/USD Decimals",
  "chainlink/link-usd-latest-round-data": "Chainlink: Get LINK/USD Latest Round Data",
  "chainlink/link-usd-decimals": "Chainlink: Get LINK/USD Decimals",
  "chainlink/usdc-usd-latest-round-data": "Chainlink: Get USDC/USD Latest Round Data",
  "chainlink/usdc-usd-decimals": "Chainlink: Get USDC/USD Decimals",
  "chainlink/dai-usd-latest-round-data": "Chainlink: Get DAI/USD Latest Round Data",
  "chainlink/dai-usd-decimals": "Chainlink: Get DAI/USD Decimals",
  "chainlink/usdt-usd-latest-round-data": "Chainlink: Get USDT/USD Latest Round Data",
  "chainlink/usdt-usd-decimals": "Chainlink: Get USDT/USD Decimals",
  "chainlink/link-eth-latest-round-data": "Chainlink: Get LINK/ETH Latest Round Data",
  "chainlink/link-eth-decimals": "Chainlink: Get LINK/ETH Decimals",
  "chainlink/btc-eth-latest-round-data": "Chainlink: Get BTC/ETH Latest Round Data",
  "chainlink/btc-eth-decimals": "Chainlink: Get BTC/ETH Decimals",
  "chainlink/latest-round-data": "Chainlink: Get Latest Round Data (Custom Feed)",
  "chainlink/get-round-data": "Chainlink: Get Round Data (Custom Feed)",
  "chainlink/latest-answer": "Chainlink: Get Latest Answer (Custom Feed)",
  "chainlink/decimals": "Chainlink: Get Decimals (Custom Feed)",
  "chainlink/description": "Chainlink: Get Description (Custom Feed)",
  "chainlink/version": "Chainlink: Get Version (Custom Feed)",
  "chronicle/eth-usd-read": "Chronicle: Read ETH/USD Value",
  "chronicle/eth-usd-read-with-age": "Chronicle: Read ETH/USD Value with Age",
  "chronicle/btc-usd-read": "Chronicle: Read BTC/USD Value",
  "chronicle/btc-usd-read-with-age": "Chronicle: Read BTC/USD Value with Age",
  "chronicle/dai-usd-read": "Chronicle: Read DAI/USD Value",
  "chronicle/dai-usd-read-with-age": "Chronicle: Read DAI/USD Value with Age",
  "chronicle/usdc-usd-read": "Chronicle: Read USDC/USD Value",
  "chronicle/usdc-usd-read-with-age": "Chronicle: Read USDC/USD Value with Age",
  "chronicle/usdt-usd-read": "Chronicle: Read USDT/USD Value",
  "chronicle/usdt-usd-read-with-age": "Chronicle: Read USDT/USD Value with Age",
  "chronicle/link-usd-read": "Chronicle: Read LINK/USD Value",
  "chronicle/link-usd-read-with-age": "Chronicle: Read LINK/USD Value with Age",
  "chronicle/read": "Chronicle: Read Oracle Value (Custom)",
  "chronicle/try-read": "Chronicle: Try Read Oracle Value (Custom)",
  "chronicle/read-with-age": "Chronicle: Read Oracle Value with Age (Custom)",
  "chronicle/try-read-with-age": "Chronicle: Try Read Oracle Value with Age (Custom)",
  "chronicle/self-kiss": "Chronicle: Whitelist on Oracle (Self)",
  "compound/supply": "Compound V3: Supply Asset",
  "compound/withdraw": "Compound V3: Withdraw Asset",
  "compound/get-balance": "Compound V3: Get Base Balance",
  "compound/get-collateral-balance": "Compound V3: Get Collateral Balance",
  "compound/get-borrow-balance": "Compound V3: Get Borrow Balance",
  "compound/get-utilization": "Compound V3: Get Utilization",
  "compound/get-supply-rate": "Compound V3: Get Supply Rate",
  "compound/get-borrow-rate": "Compound V3: Get Borrow Rate",
  "compound/get-total-supply": "Compound V3: Get Total Supply",
  "compound/get-total-borrow": "Compound V3: Get Total Borrow",
  "compound/is-liquidatable": "Compound V3: Is Liquidatable",
  "compound/get-num-assets": "Compound V3: Get Number of Assets",
  "cowswap/get-domain-separator": "CoW Swap: Get Domain Separator",
  "cowswap/get-vault-relayer": "CoW Swap: Get Vault Relayer",
  "cowswap/get-filled-amount": "CoW Swap: Get Order Fill Amount",
  "cowswap/get-pre-signature": "CoW Swap: Get Pre-Signature Status",
  "cowswap/set-pre-signature": "CoW Swap: Set Pre-Signature",
  "cowswap/invalidate-order": "CoW Swap: Invalidate Order",
  "cowswap/check-single-order": "CoW Swap: Check Conditional Order",
  "cowswap/get-cabinet": "CoW Swap: Get Cabinet Value",
  "cowswap/remove-conditional-order": "CoW Swap: Remove Conditional Order",
  "cowswap/create-conditional-order": "CoW Swap: Create Conditional Order",
  "curve/get-dy": "Curve: Get Expected Output",
  "curve/get-virtual-price": "Curve: Get Virtual Price",
  "curve/get-coin": "Curve: Get Coin Address",
  "curve/get-pool-balance": "Curve: Get Pool Balance",
  "curve/calc-withdraw-one-coin": "Curve: Calculate Withdraw One Coin",
  "curve/exchange": "Curve: Exchange Tokens",
  "curve/remove-liquidity-one-coin": "Curve: Remove Liquidity (Single Coin)",
  "curve/crv-balance-of": "Curve: Get CRV Balance",
  "curve/crv-approve": "Curve: Approve CRV",
  "curve/crv-transfer": "Curve: Transfer CRV",
  "ethena/vault-asset": "Ethena: Vault Underlying Asset",
  "ethena/vault-total-assets": "Ethena: Vault Total Assets",
  "ethena/vault-total-supply": "Ethena: Vault Total Supply",
  "ethena/vault-balance": "Ethena: Vault Share Balance",
  "ethena/vault-convert-to-shares": "Ethena: Convert Assets to Shares",
  "ethena/vault-convert-to-assets": "Ethena: Convert Shares to Assets",
  "ethena/vault-max-deposit": "Ethena: Max Vault Deposit",
  "ethena/vault-preview-deposit": "Ethena: Preview Vault Deposit",
  "ethena/vault-deposit": "Ethena: Vault Deposit",
  "ethena/vault-max-mint": "Ethena: Max Vault Mint",
  "ethena/vault-preview-mint": "Ethena: Preview Vault Mint",
  "ethena/vault-mint": "Ethena: Vault Mint",
  "ethena/vault-max-withdraw": "Ethena: Max Vault Withdraw",
  "ethena/vault-preview-withdraw": "Ethena: Preview Vault Withdraw",
  "ethena/vault-withdraw": "Ethena: Vault Withdraw",
  "ethena/vault-max-redeem": "Ethena: Max Vault Redeem",
  "ethena/vault-preview-redeem": "Ethena: Preview Vault Redeem",
  "ethena/vault-redeem": "Ethena: Vault Redeem",
  "ethena/cooldown-assets": "Ethena: Cooldown Assets",
  "ethena/cooldown-shares": "Ethena: Cooldown Shares",
  "ethena/get-cooldown-duration": "Ethena: Get Cooldown Duration",
  "ethena/get-cooldown-status": "Ethena: Get Cooldown Status",
  "ethena/unstake": "Ethena: Unstake (Claim After Cooldown)",
  "ethena/get-usde-balance": "Ethena: Get USDe Balance",
  "ethena/approve-usde": "Ethena: Approve USDe Spending",
  "ethena/get-ena-balance": "Ethena: Get ENA Balance",
  "frax-ether-v2/mint": "Frax Ether V2: Mint frxETH",
  "frax-ether-v2/mint-and-give": "Frax Ether V2: Mint frxETH to Recipient",
  "frax-ether-v2/mint-and-stake": "Frax Ether V2: Mint and Stake into sfrxETH",
  "frax-ether-v2/mint-paused": "Frax Ether V2: Check Mint Pause Status",
  "hyperliquid/clearinghouse-state": "Get Clearinghouse State",
  "hyperliquid/vault-details": "Get Vault Details",
  "hyperliquid/validator-summaries": "Get Validator Summaries",
  "hyperliquid/funding-history": "Get Funding History",
  "hyperliquid/spot-deploy-state": "Get Spot Deploy State",
  "hyperliquid/referral": "Get Referral State",
  "hyperliquid/sub-accounts": "Get Sub-Accounts",
  "hyperliquid/active-asset-data": "Get Active Asset Data",
  "lido/wrap": "Lido: Wrap stETH to wstETH",
  "lido/unwrap": "Lido: Unwrap wstETH to stETH",
  "lido/get-steth-by-wsteth": "Lido: Get stETH by wstETH",
  "lido/get-wsteth-by-steth": "Lido: Get wstETH by stETH",
  "lido/steth-per-token": "Lido: stETH Per Token (Exchange Rate)",
  "lido/tokens-per-steth": "Lido: wstETH Per stETH (Inverse Rate)",
  "lido/get-wsteth-balance": "Lido: Get wstETH Balance",
  "lido/get-wsteth-total-supply": "Lido: Get wstETH Total Supply",
  "lido/get-steth-balance": "Lido: Get stETH Balance",
  "lido/approve-steth": "Lido: Approve stETH Spending",
  "morpho/get-position": "Morpho: Get Position",
  "morpho/get-market": "Morpho: Get Market",
  "morpho/get-market-params": "Morpho: Get Market Params",
  "morpho/is-authorized": "Morpho: Check Authorization",
  "morpho/set-authorization": "Morpho: Set Authorization",
  "morpho/flash-loan": "Morpho: Flash Loan",
  "morpho/supply": "Morpho: Supply",
  "morpho/withdraw": "Morpho: Withdraw",
  "morpho/supply-collateral": "Morpho: Supply Collateral",
  "morpho/borrow": "Morpho: Borrow",
  "morpho/repay": "Morpho: Repay",
  "morpho/withdraw-collateral": "Morpho: Withdraw Collateral",
  "morpho/liquidate": "Morpho: Liquidate",
  "morpho/accrue-interest": "Morpho: Accrue Interest",
  "morpho/vault-deposit": "Morpho: Vault Deposit",
  "morpho/vault-mint": "Morpho: Vault Mint",
  "morpho/vault-withdraw": "Morpho: Vault Withdraw",
  "morpho/vault-redeem": "Morpho: Vault Redeem",
  "morpho/vault-asset": "Morpho: Vault Underlying Asset",
  "morpho/vault-total-assets": "Morpho: Vault Total Assets",
  "morpho/vault-total-supply": "Morpho: Vault Total Supply",
  "morpho/vault-balance": "Morpho: Vault Share Balance",
  "morpho/vault-convert-to-assets": "Morpho: Convert Shares to Assets",
  "morpho/vault-convert-to-shares": "Morpho: Convert Assets to Shares",
  "morpho/vault-preview-deposit": "Morpho: Preview Vault Deposit",
  "morpho/vault-preview-mint": "Morpho: Preview Vault Mint",
  "morpho/vault-preview-withdraw": "Morpho: Preview Vault Withdraw",
  "morpho/vault-preview-redeem": "Morpho: Preview Vault Redeem",
  "morpho/vault-max-deposit": "Morpho: Max Vault Deposit",
  "morpho/vault-max-mint": "Morpho: Max Vault Mint",
  "morpho/vault-max-withdraw": "Morpho: Max Vault Withdraw",
  "morpho/vault-max-redeem": "Morpho: Max Vault Redeem",
  "pendle/mint-py-from-sy": "Pendle Finance: Mint PT and YT from SY",
  "pendle/redeem-py-to-sy": "Pendle Finance: Redeem PT and YT to SY",
  "pendle/get-ve-pendle-balance": "Pendle Finance: Get vePENDLE Balance",
  "pendle/get-ve-pendle-total-supply": "Pendle Finance: Get vePENDLE Total Supply",
  "pendle/get-ve-pendle-position": "Pendle Finance: Get vePENDLE Lock Position",
  "pendle/get-market-expiry": "Pendle Finance: Get Market Expiry",
  "pendle/is-market-expired": "Pendle Finance: Is Market Expired",
  "pendle/get-lp-balance": "Pendle Finance: Get LP Balance",
  "pendle/get-active-lp-balance": "Pendle Finance: Get Active LP Balance",
  "pendle/get-pt-balance": "Pendle Finance: Get PT Balance",
  "pendle/is-pt-expired": "Pendle Finance: Is PT Expired",
  "pendle/get-yt-balance": "Pendle Finance: Get YT Balance",
  "pendle/get-sy-balance": "Pendle Finance: Get SY Balance",
  "pendle/get-sy-exchange-rate": "Pendle Finance: Get SY Exchange Rate",
  "robinhood/get-stock-price": "Get Stock Token Price",
  "robinhood/get-stock-position": "Get Stock Token Position",
  "robinhood/trade-stock-token": "Trade Stock Token",
  "robinhood/stock-market-status": "Stock Market Status",
  "rocket-pool/get-exchange-rate": "Rocket Pool: Get rETH Exchange Rate",
  "rocket-pool/balance-of": "Rocket Pool: Get rETH Balance",
  "rocket-pool/total-supply": "Rocket Pool: Get rETH Total Supply",
  "rocket-pool/get-total-collateral": "Rocket Pool: Get Total ETH Collateral",
  "rocket-pool/burn": "Rocket Pool: Burn rETH for ETH",
  "rocket-pool/deposit": "Rocket Pool: Deposit ETH for rETH",
  "safe/get-owners": "Safe: Get Owners",
  "safe/get-threshold": "Safe: Get Threshold",
  "safe/is-owner": "Safe: Is Owner",
  "safe/get-nonce": "Safe: Get Nonce",
  "safe/is-module-enabled": "Safe: Is Module Enabled",
  "safe/get-modules-paginated": "Safe: Get Modules Paginated",
  "safe/get-pending-transactions": "Get Pending Transactions",
  "sky/vault-deposit": "Sky: Vault Deposit",
  "sky/vault-mint": "Sky: Vault Mint",
  "sky/vault-withdraw": "Sky: Vault Withdraw",
  "sky/vault-redeem": "Sky: Vault Redeem",
  "sky/vault-asset": "Sky: Vault Underlying Asset",
  "sky/vault-total-assets": "Sky: Vault Total Assets",
  "sky/vault-total-supply": "Sky: Vault Total Supply",
  "sky/vault-balance": "Sky: Vault Share Balance",
  "sky/vault-convert-to-assets": "Sky: Convert Shares to Assets",
  "sky/vault-convert-to-shares": "Sky: Convert Assets to Shares",
  "sky/vault-preview-deposit": "Sky: Preview Vault Deposit",
  "sky/vault-preview-mint": "Sky: Preview Vault Mint",
  "sky/vault-preview-withdraw": "Sky: Preview Vault Withdraw",
  "sky/vault-preview-redeem": "Sky: Preview Vault Redeem",
  "sky/vault-max-deposit": "Sky: Max Vault Deposit",
  "sky/vault-max-mint": "Sky: Max Vault Mint",
  "sky/vault-max-withdraw": "Sky: Max Vault Withdraw",
  "sky/vault-max-redeem": "Sky: Max Vault Redeem",
  "sky/st-usds-vault-deposit": "Sky: stUSDS Vault Deposit",
  "sky/st-usds-vault-mint": "Sky: stUSDS Vault Mint",
  "sky/st-usds-vault-withdraw": "Sky: stUSDS Vault Withdraw",
  "sky/st-usds-vault-redeem": "Sky: stUSDS Vault Redeem",
  "sky/st-usds-vault-asset": "Sky: stUSDS Vault Underlying Asset",
  "sky/st-usds-vault-total-assets": "Sky: stUSDS Vault Total Assets",
  "sky/st-usds-vault-total-supply": "Sky: stUSDS Vault Total Supply",
  "sky/st-usds-vault-balance": "Sky: stUSDS Vault Share Balance",
  "sky/st-usds-vault-convert-to-assets": "Sky: stUSDS Convert Shares to Assets",
  "sky/st-usds-vault-convert-to-shares": "Sky: stUSDS Convert Assets to Shares",
  "sky/st-usds-vault-preview-deposit": "Sky: stUSDS Preview Vault Deposit",
  "sky/st-usds-vault-preview-mint": "Sky: stUSDS Preview Vault Mint",
  "sky/st-usds-vault-preview-withdraw": "Sky: stUSDS Preview Vault Withdraw",
  "sky/st-usds-vault-preview-redeem": "Sky: stUSDS Preview Vault Redeem",
  "sky/st-usds-vault-max-deposit": "Sky: stUSDS Max Vault Deposit",
  "sky/st-usds-vault-max-mint": "Sky: stUSDS Max Vault Mint",
  "sky/st-usds-vault-max-withdraw": "Sky: stUSDS Max Vault Withdraw",
  "sky/st-usds-vault-max-redeem": "Sky: stUSDS Max Vault Redeem",
  "sky/get-usds-balance": "Sky: Get USDS Balance",
  "sky/approve-usds": "Sky: Approve USDS Spending",
  "sky/get-dai-balance": "Sky: Get DAI Balance",
  "sky/approve-dai": "Sky: Approve DAI Spending",
  "sky/get-sky-balance": "Sky: Get SKY Balance",
  "sky/convert-dai-to-usds": "Sky: Convert DAI to USDS",
  "sky/convert-usds-to-dai": "Sky: Convert USDS to DAI",
  "sky/convert-mkr-to-sky": "Sky: Convert MKR to SKY",
  "spark/supply": "Spark: Supply Asset",
  "spark/withdraw": "Spark: Withdraw Asset",
  "spark/borrow": "Spark: Borrow Asset",
  "spark/repay": "Spark: Repay Debt",
  "spark/set-collateral": "Spark: Set Asset as Collateral",
  "spark/get-user-account-data": "Spark: Get User Account Data",
  "spark/get-user-reserve-data": "Spark: Get User Reserve Data",
  "spark/vault-deposit": "Spark: Vault Deposit",
  "spark/vault-mint": "Spark: Vault Mint",
  "spark/vault-withdraw": "Spark: Vault Withdraw",
  "spark/vault-redeem": "Spark: Vault Redeem",
  "spark/vault-asset": "Spark: Vault Underlying Asset",
  "spark/vault-total-assets": "Spark: Vault Total Assets",
  "spark/vault-total-supply": "Spark: Vault Total Supply",
  "spark/vault-balance": "Spark: Vault Share Balance",
  "spark/vault-convert-to-assets": "Spark: Convert Shares to Assets",
  "spark/vault-convert-to-shares": "Spark: Convert Assets to Shares",
  "spark/vault-preview-deposit": "Spark: Preview Vault Deposit",
  "spark/vault-preview-mint": "Spark: Preview Vault Mint",
  "spark/vault-preview-withdraw": "Spark: Preview Vault Withdraw",
  "spark/vault-preview-redeem": "Spark: Preview Vault Redeem",
  "spark/vault-max-deposit": "Spark: Max Vault Deposit",
  "spark/vault-max-mint": "Spark: Max Vault Mint",
  "spark/vault-max-withdraw": "Spark: Max Vault Withdraw",
  "spark/vault-max-redeem": "Spark: Max Vault Redeem",
  "superfluid/create-flow": "Superfluid: Open Money Stream",
  "superfluid/update-flow": "Superfluid: Update Stream Rate",
  "superfluid/delete-flow": "Superfluid: Close Money Stream",
  "superfluid/get-flow": "Superfluid: Read Flow Between Two Addresses",
  "superfluid/get-cfa-net-flow": "Superfluid: Read CFA Net Flow Rate of an Address",
  "superfluid/grant-flow-operator": "Superfluid: Grant Flow-Operator Permissions",
  "superfluid/create-pool": "Superfluid: Create Distribution Pool",
  "superfluid/update-member-units": "Superfluid: Set Member Units in a Pool",
  "superfluid/distribute": "Superfluid: Instant Distribution to a Pool",
  "superfluid/distribute-flow": "Superfluid: Stream Into a Pool",
  "superfluid/connect-pool": "Superfluid: Connect to a Pool (Member Opt-In)",
  "superfluid/get-net-flow": "Superfluid: Read Net Flow Rate of an Address",
  "superfluid/wrap": "Superfluid: Wrap to SuperToken",
  "superfluid/unwrap": "Superfluid: Unwrap from SuperToken",
  "superfluid/get-super-token-balance": "Superfluid: Get SuperToken Balance",
  "superfluid/get-underlying-token": "Superfluid: Get Underlying ERC-20 Address",
  "uniswap/get-pool": "Uniswap V3: Get Pool Address",
  "uniswap/get-position": "Uniswap V3: Get Position Details",
  "uniswap/balance-of": "Uniswap V3: Get Position Count",
  "uniswap/owner-of": "Uniswap V3: Get Position Owner",
  "uniswap/approve-position": "Uniswap V3: Approve Position Transfer",
  "uniswap/transfer-position": "Uniswap V3: Transfer Position NFT",
  "uniswap/burn-position": "Uniswap V3: Burn Empty Position",
  "uniswap/swap-exact-input": "Uniswap V3: Swap Exact Input",
  "uniswap/swap-exact-output": "Uniswap V3: Swap Exact Output",
  "uniswap/quote-exact-input": "Uniswap V3: Quote Exact Input",
  "uniswap/quote-exact-output": "Uniswap V3: Quote Exact Output",
  "wrapped/wrap": "Wrapped: Wrap Native Token",
  "wrapped/unwrap": "Wrapped: Unwrap Wrapped Token",
  "wrapped/balance-of": "Wrapped: Check Wrapped Token Balance",
  "yearn/vault-deposit": "Yearn V3: Vault Deposit",
  "yearn/vault-mint": "Yearn V3: Vault Mint",
  "yearn/vault-withdraw": "Yearn V3: Vault Withdraw",
  "yearn/vault-redeem": "Yearn V3: Vault Redeem",
  "yearn/vault-asset": "Yearn V3: Vault Underlying Asset",
  "yearn/vault-total-assets": "Yearn V3: Vault Total Assets",
  "yearn/vault-total-supply": "Yearn V3: Vault Total Supply",
  "yearn/vault-balance": "Yearn V3: Vault Share Balance",
  "yearn/vault-convert-to-assets": "Yearn V3: Convert Shares to Assets",
  "yearn/vault-convert-to-shares": "Yearn V3: Convert Assets to Shares",
  "yearn/vault-preview-deposit": "Yearn V3: Preview Vault Deposit",
  "yearn/vault-preview-mint": "Yearn V3: Preview Vault Mint",
  "yearn/vault-preview-withdraw": "Yearn V3: Preview Vault Withdraw",
  "yearn/vault-preview-redeem": "Yearn V3: Preview Vault Redeem",
  "yearn/vault-max-deposit": "Yearn V3: Max Vault Deposit",
  "yearn/vault-max-mint": "Yearn V3: Max Vault Mint",
  "yearn/vault-max-withdraw": "Yearn V3: Max Vault Withdraw",
  "yearn/vault-max-redeem": "Yearn V3: Max Vault Redeem",
  "yearn/get-price-per-share": "Yearn V3: Price Per Share",
  "yearn/get-total-idle": "Yearn V3: Total Idle Assets",
  "yearn/get-total-debt": "Yearn V3: Total Debt",
  "yearn/get-is-shutdown": "Yearn V3: Is Vault Shutdown",
  "yearn/get-api-version": "Yearn V3: API Version",
  "yearn/get-profit-max-unlock-time": "Yearn V3: Profit Max Unlock Time",
  "yearn/get-full-profit-unlock-date": "Yearn V3: Full Profit Unlock Date",
  "yearn/get-accountant": "Yearn V3: Vault Accountant",
  "yearn/get-deposit-limit": "Yearn V3: Deposit Limit",
  "yearn/get-role-manager": "Yearn V3: Role Manager",
  "yearn/get-use-default-queue": "Yearn V3: Use Default Queue",
  "yearn/get-minimum-total-idle": "Yearn V3: Minimum Total Idle",
  "yearn/get-vault-decimals": "Yearn V3: Vault Decimals",
  "blockscout/get-address-balance": "Get Address Balance",
  "blockscout/get-address-info": "Get Address Info",
  "blockscout/get-address-counters": "Get Address Counters",
  "blockscout/get-transaction": "Get Transaction",
  "blockscout/get-token-info": "Get Token Info",
  "code/run-code": "Run Code",
  "discord/send-message": "Send Discord Message",
  "elizaos/execute-agent-action": "Trigger Agent Action",
  "evm-chain/chain-info": "Chain info",
  "evm-chain/eth-balance": "Native token balance",
  "evm-chain/erc20-balance": "ERC-20 balance",
  "evm-chain/gas-price": "Gas price",
  "math/aggregate": "Aggregate",
  "sendgrid/send-email": "Send Email",
  "slack/send-message": "Send Slack Message",
  "telegram/send-message": "Send Telegram Message",
  "tempo/transfer-with-memo": "Transfer with Memo",
  "tempo/batch-payout": "Batch Payout",
  "tempo/dex-swap": "Swap Stablecoins",
  "tempo/hold-payment": "Sign & Hold Payment",
  "web3/check-balance": "Get Native Token Balance",
  "web3/check-token-balance": "Get ERC20 Token Balance",
  "web3/get-spl-token-balance": "Get SPL Token Balance",
  "web3/transfer-funds": "Transfer Native Token",
  "web3/transfer-token": "Transfer ERC20 Token",
  "web3/transfer-spl-token": "Transfer SPL Token",
  "web3/send-raw-solana-instruction": "Send Raw Solana Instruction",
  "web3/call-solana-program-anchor": "Call Solana Program (Anchor)",
  "web3/read-solana-account": "Read Solana Account",
  "web3/read-solana-program-anchor": "Read Solana Program (Anchor)",
  "web3/query-solana-program-events": "Query Solana Program Events",
  "web3/read-contract": "Read Contract",
  "web3/get-transaction": "Get Transaction",
  "web3/decode-calldata": "Decode Calldata",
  "web3/assess-risk": "Assess Transaction Risk",
  "web3/query-events": "Query Contract Events",
  "web3/query-transactions": "Query Transaction History",
  "web3/batch-read-contract": "Batch Read Contract",
  "web3/batch-write-contract": "Batch Write Contract",
  "web3/approve-token": "Approve ERC20 Token",
  "web3/check-allowance": "Check ERC20 Allowance",
  "web3/write-contract": "Write Contract",
  "web3/sign-typed-data": "Sign Typed Data (EIP-712)",
  "webhook/send-webhook": "Send Webhook",
  "Send Slack Message": "Send Slack Message",
  "safe-wallet/get-owners": "Safe: Get Owners",
  "safe-wallet/get-threshold": "Safe: Get Threshold",
  "safe-wallet/is-owner": "Safe: Is Owner",
  "safe-wallet/get-nonce": "Safe: Get Nonce",
  "safe-wallet/is-module-enabled": "Safe: Is Module Enabled",
  "safe-wallet/get-modules-paginated": "Safe: Get Modules Paginated",
  "safe-wallet/get-pending-transactions": "Get Pending Transactions",
  "Check Balance": "Get Native Token Balance",
  "Transfer Funds": "Transfer Native Token",
  "Read Contract": "Read Contract",
  "Write Contract": "Write Contract",
};

/**
 * Get a step importer for an action type
 */
export function getStepImporter(actionType: string): StepImporter | undefined {
  return PLUGIN_STEP_IMPORTERS[actionType];
}

/**
 * Get the human-readable label for an action type
 */
export function getActionLabel(actionType: string): string | undefined {
  return ACTION_LABELS[actionType];
}
