export default {
  index: "Overview",
  authentication: "Authentication",
  "headless-onboarding": "Headless Onboarding",
  workflows: "Workflows",
  executions: "Executions",
  "direct-execution": "Direct Execution",
  analytics: "Analytics",
  integrations: "Integrations",
  projects: "Projects",
  tags: "Tags",
  chains: "Chains",
  user: "User",
  organizations: "Organizations",
  "api-keys": "API Keys",
  errors: "Errors",
};
