export default {
  index: "Overview",
  "getting-started": "Getting Started",
  concepts: "Core Concepts",
  "platform-reference": "Platform Reference",
  keepers: "Nodes",
  workflows: "Workflows",
  plugins: "Plugins",
  "keeper-runs": "Keeper Runs",
  notifications: "Notifications",
  "wallet-management": "Wallet Management",
  "users-teams-orgs": "Users and Organizations",
  practices: "Best Practices",
  agent: "Agent Tools",
  guides: "Guides",
  FAQ: "FAQ",
  api: "API",
  cli: "CLI",
};
